-- Roll back canonical reset to the immediately preceding Finance OS v2 opening state. No bank movement is performed.
update public.finance_accounts set display_name='BIDV Tuấn',opening_balance=13790269,current_balance=13790269,bank_balance=13790269,book_balance=13790269,balance_as_of='2026-09-30',ownership_status='VERIFIED',verification_status='VERIFIED',record_status='ACTIVE',account_roles=array['PERSONAL_OPERATING_ACCOUNT'],reconciliation_status='MATCHED',is_restricted_cash=false,source='OWNER_CUTOVER',source_reference='DEC-FIN-CUTOVER-20260929-001',updated_at=now() where account_code='OPEN-BIDV-TUAN';
update public.finance_accounts set display_name='HKD Tuấn',opening_balance=4563428,current_balance=4563428,bank_balance=4563428,book_balance=4563428,balance_as_of='2026-09-30',ownership_status='VERIFIED',verification_status='VERIFIED',record_status='ACTIVE',account_roles=array['BUSINESS_OPERATING_ACCOUNT'],reconciliation_status='MATCHED',is_restricted_cash=false,source='OWNER_CUTOVER',source_reference='DEC-FIN-CUTOVER-20260929-001',updated_at=now() where account_code='OPEN-HKD-TUAN';
update public.finance_accounts set display_name='TPBank Tuấn',record_status='ACTIVE',ownership_status='NEED_VERIFY',verification_status='VERIFIED',account_roles=array['NEED_VERIFY'],reconciliation_status='MATCHED',source='OWNER_CUTOVER',source_reference='DEC-FIN-CUTOVER-20260929-001',updated_at=now() where account_code='OPEN-TPBANK-TUAN';
update public.finance_accounts set opening_balance=null,current_balance=null,bank_balance=null,book_balance=null,ownership_status='NEED_VERIFY',verification_status='NEED_VERIFY',reconciliation_status='NEED_VERIFY',source='OWNER_FINANCE_POLICY',source_reference='FIN-OPS-V2-20260929',updated_at=now() where account_code in ('ROLE-TPBANK-SAFETY','ROLE-TPBANK-TAX');
update public.personal_finance_accounts set record_status='ACTIVE',status_reason=null,status_changed_at=now(),updated_at=now() where name='Quỹ an toàn' and source='TUAN OS — Mô hình tài chính gia đình';
update public.personal_finance_accounts set record_status='SUPERSEDED',status_reason='Rollback of 30/09 finance reset',status_changed_at=now(),updated_at=now() where source='OWNER_APPROVED_RESET' and external_key in ('CUTOVER-BIDV-888-PERSONAL-20260930','CUTOVER-TPBANK-888-SAFETY-20260930');
update public.finance_opening_positions set record_status='SUPERSEDED',updated_at=now() where position_code='OPEN-BUSINESS-CASH-CONSOLIDATED-20260930';
update public.finance_employee_advances set record_status='SUPERSEDED',status='VOIDED',updated_at=now() where external_key in ('OPEN-ADVANCE-SEP2026-CHI-NAM','OPEN-ADVANCE-SEP2026-HOANG');
alter table public.business_finance_transactions drop constraint if exists business_finance_transactions_transaction_type_check;
alter table public.business_finance_transactions add constraint business_finance_transactions_transaction_type_check check(transaction_type = any(array['REVENUE','CASH_IN','CASH_OUT','COGS','PAYROLL','OPEX','OTA_COMMISSION','UTILITY','AR_SETTLEMENT','AP_PAYMENT','TAX','INTEREST','DEBT_PRINCIPAL','OWNER_DISTRIBUTION','OWNER_CONTRIBUTION','TRANSFER','OTHER']::text[]));
update public.finance_master_data set is_active=false,record_status='INACTIVE',updated_at=now() where master_data_type='TRANSACTION_TYPE' and code='EMPLOYEE_ADVANCE';
update public.finance_month_end_close_items set is_current=false,updated_at=now() where close_month='2026-10-01' and workflow_version='v3';
update public.finance_month_end_close_items set is_current=true,workflow_version='v2',updated_at=now() where close_month='2026-10-01' and checklist_code in ('BANK_RECON','OTA_RECON','AP_RECORD','PAYROLL_CLOSE_V2','UTILITIES_CLOSE_V2','OTA_COMMISSION_V2','REVENUE_CLOSE','EXPENSE_CLOSE','PBT_CALC','TAX_PROVISION','TAX_RESERVE','PAT_CALC','BANK_CASH_CALC','OPERATING_RESERVE','DISTRIBUTABLE_CALC','ALLOCATION_PROPOSAL','CEO_ADJUST','CEO_APPROVE','TRANSFER_EXECUTION','BANK_CONFIRMATION','POST_TRANSFER_RECON','PERSONAL_FINANCE_UPDATE_V2','DEBT_UPDATE_V2','EMERGENCY_FUND_UPDATE_V2','MONTHLY_REVIEW_V2');
