import { FREEDOM_KPIS, canonicalKpiStatus, changePercent, gapToTarget, kpiTrend, targetProgress, type FreedomKpiCode, type FreedomStatus, type FreedomTrend } from "@/server/finance/financial-freedom-core";
import { saveFinancialFreedomTarget } from "./actions";

type Row = Record<string, unknown>;

type Props = {
  month: string;
  position: Row | null;
  monthly: Row | null;
  goals: Row[];
  snapshots: Row[];
  transactions: Row[];
  historyTransactions: Row[];
  debts: Row[];
  statuses: {
    netWorth: string; assets: string; debt: string; cash: string; emergency: string; income: string; expense: string; cashflow: string;
  };
  updated: { assets?: unknown; debt?: unknown; account?: unknown; transaction?: unknown };
  selectedKpi?: string;
  migrationMissing: boolean;
  cutover: Row | null;
};

const fmt = new Intl.NumberFormat("vi-VN",{maximumFractionDigits:0});
function money(v: unknown) { const n=Number(v); return Number.isFinite(n) ? `${fmt.format(n)} đ` : "—"; }
function dateVi(v: unknown) { if(!v)return "—"; const d=new Date(String(v)); return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"Asia/Ho_Chi_Minh"}).format(d); }
function num(v: unknown): number | null { const n=Number(v); return Number.isFinite(n)?n:null; }
function monthLabel(v:string){const [y,m]=v.slice(0,7).split("-");return `Th${Number(m)}/${y.slice(2)}`;}
function statusVi(v: FreedomStatus|string){return ({ON_TRACK:"ĐÚNG TIẾN ĐỘ",AT_RISK:"CÓ RỦI RO",OFF_TRACK:"CHẬM TIẾN ĐỘ",ACHIEVED:"ĐÃ ĐẠT",NEED_VERIFY:"CẦN XÁC MINH",NO_DATA:"CHƯA CÓ DỮ LIỆU",VERIFIED:"ĐÚNG TIẾN ĐỘ",STALE:"CẦN XÁC MINH"} as Record<string,string>)[v]??"CẦN XÁC MINH";}
function statusClass(v: FreedomStatus|string){if(v==="ACHIEVED"||v==="ON_TRACK"||v==="VERIFIED")return "bg-[#dff8e9] text-[#15924a]";if(v==="AT_RISK"||v==="NEED_VERIFY"||v==="STALE")return "bg-[#fff0c9] text-[#b56c00]";if(v==="OFF_TRACK")return "bg-[#ffe1df] text-[#e03a32]";return "bg-[#edf1f6] text-[#667894]";}
function trendVi(v:FreedomTrend){return v==="IMPROVING"?"↑":v==="WORSENING"?"↓":v==="STABLE"?"→":"—";}
function trendClass(v:FreedomTrend){return v==="IMPROVING"?"text-[#12a150]":v==="WORSENING"?"text-[#ef3c3c]":"text-[#556987]";}

function Icon({kind}:{kind:string}){const common="h-5 w-5"; if(kind==="bank")return <svg className={common} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 10h18M5 10v8m5-8v8m4-8v8m5-8v8M3 21h18M12 3 3 7h18l-9-4Z"/></svg>;if(kind==="debt")return <svg className={common} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 10h10M7 14h5"/></svg>;if(kind==="wallet")return <svg className={common} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 6h14a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h12"/><path d="M16 11h6v4h-6a2 2 0 1 1 0-4Z"/></svg>;return <svg className={common} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 20V10m5 10V4m5 16v-7m5 7V7"/><path d="m3 9 6-5 5 8 6-6"/></svg>}

function OverviewCard({label,value,status,source,updated,sourceUpdated,icon,tone,href}:{label:string;value:string;status:string;source:string;updated?:unknown;sourceUpdated?:unknown;icon:string;tone:string;href:string}){
  return <div className="relative rounded-[10px] border border-[#d5e3f1] bg-white p-3 shadow-[0_1px_3px_rgba(20,55,90,.06)]">
    <div className={`absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-lg ${tone}`}><Icon kind={icon}/></div>
    <div className="pr-10 text-[10px] font-bold text-[#54709a]">{label}</div><div className="mt-1 text-[19px] font-black tracking-tight text-[#0b2d62]">{value}</div>
    <div className="mt-1"><span className={`inline-flex rounded-md px-2 py-1 text-[8px] font-black ${statusClass(status)}`}>{statusVi(status)}</span></div>
    <div className="mt-2 space-y-[2px] text-[8px] leading-3 text-[#7890b0]"><div>Nguồn: {source}</div><div>App cập nhật: {dateVi(updated)}</div><div>Nguồn cập nhật: {dateVi(sourceUpdated)}</div></div>
    <div className="mt-2 flex gap-4 text-[9px] font-bold text-[#0874eb]"><a href="#data-source-map">Xem nguồn</a><a href={href}>Cập nhật dữ liệu</a></div>
  </div>;
}

type Metric = {code:FreedomKpiCode;label:string;direction:"UP"|"DOWN";unit:string;actual:number|null;verified:boolean;longTarget:number|null;annualTarget:number|null;monthTarget:number|null;opening?:number|null;prev:number|null;gap:number|null;progress:number|null;status:FreedomStatus;trend:FreedomTrend;changePct:number|null};

function LineChart({title,kpi,snapshots,tone}:{title:string;kpi:FreedomKpiCode;snapshots:Row[];tone:"blue"|"red"}){
  const rows=snapshots.filter(x=>String(x.kpi_code)===kpi&&num(x.actual_value)!==null).sort((a,b)=>String(a.period).localeCompare(String(b.period))).slice(-12);
  const vals=rows.map(x=>num(x.actual_value) as number);
  const min=vals.length?Math.min(...vals):0,max=vals.length?Math.max(...vals):1,range=Math.max(1,max-min);
  const pts=rows.map((x,i)=>`${20+(i*Math.max(1,460/(Math.max(rows.length-1,1))))},${95-((num(x.actual_value) as number-min)/range)*65}`).join(" ");
  return <div className="rounded-[10px] border border-[#d5e3f1] bg-white p-3"><div className="flex justify-between"><h3 className="text-[12px] font-black text-[#102d5f]">{title}</h3><span className="text-[8px] text-[#8193ae]">lịch sử snapshot</span></div>
    {rows.length?<><svg viewBox="0 0 500 115" className="mt-2 h-[120px] w-full"><path d="M20 100H485" stroke="#dbe6f1"/><polyline points={pts} fill="none" stroke={tone==="blue"?"#1478ee":"#ff4239"} strokeWidth="3"/>{rows.map((x,i)=>{const [px,py]=pts.split(" ")[i].split(",");return <circle key={i} cx={px} cy={py} r="3.2" fill={tone==="blue"?"#1478ee":"#ff4239"}/>})}</svg><div className="flex justify-between text-[8px] text-[#778aa8]">{rows.map(x=><span key={String(x.period)}>{monthLabel(String(x.period))}</span>)}</div></>:<div className="grid h-[145px] place-items-center text-[10px] font-semibold text-[#8a99ae]">CHƯA CÓ DỮ LIỆU LỊCH SỬ</div>}
  </div>;
}

function IncomeExpenseChart({history}:{history:Row[]}){
  const now=new Date(); const keys=Array.from({length:12},(_,i)=>{const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-11+i,1));return d.toISOString().slice(0,7)});
  const values=keys.map(k=>{const rows=history.filter(x=>String(x.transaction_date??"").startsWith(k)&&x.record_status==="ACTIVE"&&x.verification_status==="VERIFIED");return {k,income:rows.filter(x=>x.transaction_type==="INCOME").reduce((s,x)=>s+Number(x.amount??0),0),expense:rows.filter(x=>x.transaction_type==="EXPENSE").reduce((s,x)=>s+Number(x.amount??0),0)}}); const max=Math.max(1,...values.flatMap(x=>[x.income,x.expense]));
  return <div className="rounded-[10px] border border-[#d5e3f1] bg-white p-3"><div className="flex justify-between"><h3 className="text-[12px] font-black text-[#102d5f]">Thu nhập vs Chi phí</h3><div className="text-[8px] text-[#7287a5]"><span className="text-[#1478ee]">● Thu nhập</span> · <span className="text-[#ff8d61]">● Chi phí</span></div></div><div className="mt-3 flex h-[125px] items-end gap-2 border-b border-[#dce6f1] px-1">{values.map(x=><div key={x.k} className="flex h-full flex-1 items-end justify-center gap-[2px]"><div className="w-[38%] rounded-t bg-[#1478ee]" style={{height:`${Math.max(x.income?4:0,x.income/max*100)}%`}}/><div className="w-[38%] rounded-t bg-[#ff8d61]" style={{height:`${Math.max(x.expense?4:0,x.expense/max*100)}%`}}/></div>)}</div><div className="mt-1 flex justify-between text-[7px] text-[#7b8da7]">{keys.map(k=><span key={k}>Th{Number(k.slice(5,7))}</span>)}</div></div>;
}

export function FinancialFreedomDashboard(p:Props){
  const goalFor=(code:string,level:string)=>p.goals.filter(x=>x.status==="ACTIVE"&&x.verification_status==="VERIFIED"&&x.kpi_code===code&&x.target_level===level).filter(x=>level!=="MONTHLY"||String(x.target_period).slice(0,7)===p.month.slice(0,7)).filter(x=>level!=="ANNUAL"||Number(x.target_year)===Number(p.month.slice(0,4))).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))[0];
  const prevPeriod=(()=>{const d=new Date(p.month+"T00:00:00Z");d.setUTCMonth(d.getUTCMonth()-1);return d.toISOString().slice(0,10)})();
  const prev=(code:string)=>num(p.snapshots.find(x=>x.kpi_code===code&&String(x.period).slice(0,10)===prevPeriod)?.actual_value);
  const sustainable=p.transactions.filter(x=>x.transaction_type==="INCOME"&&x.is_sustainable_income===true&&x.verification_status==="VERIFIED"&&x.record_status==="ACTIVE").reduce((s,x)=>s+Number(x.amount??0),0);
  const essential=p.transactions.filter(x=>x.transaction_type==="EXPENSE"&&x.is_essential===true&&x.verification_status==="VERIFIED"&&x.record_status==="ACTIVE").reduce((s,x)=>s+Number(x.amount??0),0);
  const unverifiedSustainable=p.transactions.some(x=>x.transaction_type==="INCOME"&&x.is_sustainable_income===true&&x.verification_status!=="VERIFIED"&&x.record_status==="ACTIVE");
  const unverifiedEssential=p.transactions.some(x=>x.transaction_type==="EXPENSE"&&x.is_essential===true&&x.verification_status!=="VERIFIED"&&x.record_status==="ACTIVE");
  const openingDebt=p.debts.filter(x=>x.status==="ACTIVE"&&x.verification_status==="VERIFIED").reduce((s,x)=>s+Number(x.opening_principal??0),0);
  const actualMap:Record<string,{value:number|null;verified:boolean;opening?:number|null}>={
    NET_WORTH:{value:num(p.position?.net_worth),verified:p.statuses.netWorth==="VERIFIED"},
    TOTAL_DEBT:{value:p.statuses.debt==="VERIFIED"?num(p.position?.verified_liabilities):null,verified:p.statuses.debt==="VERIFIED",opening:openingDebt||null},
    NET_CASH_FLOW:{value:p.statuses.cashflow==="VERIFIED"?num(p.monthly?.personal_net_cash_flow):null,verified:p.statuses.cashflow==="VERIFIED"},
    SUSTAINABLE_INCOME:{value:sustainable>0&&!unverifiedSustainable?sustainable:null,verified:sustainable>0&&!unverifiedSustainable},
    ESSENTIAL_EXPENSE:{value:essential>0&&!unverifiedEssential?essential:null,verified:essential>0&&!unverifiedEssential},
    EMERGENCY_FUND:{value:p.statuses.emergency==="VERIFIED"?num(p.position?.emergency_fund):null,verified:p.statuses.emergency==="VERIFIED"},
    LIQUID_CASH:{value:p.statuses.cash==="VERIFIED"?num(p.position?.available_cash):null,verified:p.statuses.cash==="VERIFIED"},
    DEBT_SERVICE_COVERAGE:{value:null,verified:false}, SAVINGS_RATE:{value:null,verified:false},
  };
  const metrics:Metric[]=FREEDOM_KPIS.map(k=>{const a=actualMap[k.code];const lt=num(goalFor(k.code,"LONG_TERM")?.target_amount),annual=num(goalFor(k.code,"ANNUAL")?.target_amount),mt=num(goalFor(k.code,"MONTHLY")?.target_amount);const activeTarget=mt??annual??lt;const gap=gapToTarget(a.value,activeTarget,k.direction);const progress=targetProgress({actual:a.value,target:activeTarget,direction:k.direction,opening:a.opening});const pv=prev(k.code);return {code:k.code,label:k.label,direction:k.direction,unit:k.unit,actual:a.value,verified:a.verified,longTarget:lt,annualTarget:annual,monthTarget:mt,opening:a.opening,prev:pv,gap,progress,status:canonicalKpiStatus({actual:a.value,target:activeTarget,direction:k.direction,verified:a.verified}),trend:kpiTrend(a.value,pv,k.direction),changePct:changePercent(a.value,pv)}});
  const primary=metrics.filter(x=>FREEDOM_KPIS.find(k=>k.code===x.code)?.primary);
  const selected=metrics.find(x=>x.code===p.selectedKpi);
  const totalAssets=p.statuses.assets==="VERIFIED"?num(p.position?.verified_assets):null;
  const overview=[
    ["Tài sản ròng",p.statuses.netWorth==="VERIFIED"?money(p.position?.net_worth):"—",p.statuses.netWorth,"Owner Consolidated View",p.updated.assets,p.updated.assets,"chart","bg-[#e9f3ff] text-[#0874eb]","#input-account"],
    ["Tổng tài sản",p.statuses.assets==="VERIFIED"?money(totalAssets):"—",p.statuses.assets,"Tài khoản + tài sản",p.updated.assets,p.updated.assets,"bank","bg-[#e8f3ff] text-[#0874eb]","#input-asset"],
    ["Tổng nợ",p.statuses.debt==="VERIFIED"?money(p.position?.verified_liabilities):"—",p.statuses.debt,"Personal Finance · Nợ",p.updated.debt,p.updated.debt,"debt","bg-[#ffe9e8] text-[#ff4038]","#input-debt"],
    ["Tiền khả dụng",p.statuses.cash==="VERIFIED"?money(p.position?.available_cash):"—",p.statuses.cash,"Tài khoản thanh khoản",p.updated.account,p.updated.account,"wallet","bg-[#e5f8ed] text-[#16a45a]","#input-account"],
    ["Thu nhập tháng",p.statuses.income==="VERIFIED"?money(p.monthly?.personal_income_actual):"—",p.statuses.income,"Giao dịch + phân phối thu nhập",p.updated.transaction,p.updated.transaction,"chart","bg-[#e5f8ed] text-[#16a45a]","#input-transaction"],
    ["Chi phí tháng",p.statuses.expense==="VERIFIED"?money(p.monthly?.personal_expense_actual):"—",p.statuses.expense,"Giao dịch cá nhân",p.updated.transaction,p.updated.transaction,"debt","bg-[#ffe9e8] text-[#ff4038]","#input-transaction"],
    ["Dòng tiền ròng tháng",p.statuses.cashflow==="VERIFIED"?money(p.monthly?.personal_net_cash_flow):"—",p.statuses.cashflow,"Personal + Business↔Personal",p.updated.transaction,p.updated.transaction,"chart","bg-[#e8f3ff] text-[#0874eb]","#input-transaction"],
    ["Quỹ dự phòng",p.statuses.emergency==="VERIFIED"?money(p.position?.emergency_fund):"—",p.statuses.emergency,"Tài khoản Quỹ dự phòng",p.updated.account,p.updated.account,"wallet","bg-[#fff0dd] text-[#ff8b00]","#input-account"],
  ] as const;
  const end=new Date(p.month+"T00:00:00Z");end.setUTCMonth(end.getUTCMonth()+1);end.setUTCDate(0);const due=end.toISOString().slice(0,10);
  const actionText:Record<string,string>={NET_WORTH:"Tăng đầu tư định kỳ, rà soát tài sản chưa khai báo",TOTAL_DEBT:"Thanh toán thêm vào khoản nợ ưu tiên theo kế hoạch",NET_CASH_FLOW:"Tăng thu hoặc cắt chi không thiết yếu để cải thiện dòng tiền",EMERGENCY_FUND:"Chuyển bổ sung vào tài khoản quỹ dự phòng",SUSTAINABLE_INCOME:"Tăng nguồn thu nhập cá nhân bền vững đã xác minh",ESSENTIAL_EXPENSE:"Rà soát chi thiết yếu và loại lãng phí, không xóa giao dịch"};
  return <div id="financial-freedom" className="space-y-3">
    {p.migrationMissing?<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-[11px] font-bold text-amber-800">HOLD: migration Financial Freedom KPI chưa PASS. Không coi NO DATA = 0.</div>:null}
    <div className="grid grid-cols-1 gap-3 2xl:grid-cols-[1.12fr_.92fr]">
      <section className="rounded-[10px] border border-[#d4e2f0] bg-[#fbfdff] p-2.5"><h2 className="mb-2 text-[14px] font-black text-[#0b2c61]">1. Tổng quan</h2><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 xl:grid-cols-4">{overview.map((x,i)=><OverviewCard key={i} label={x[0]} value={x[1]} status={x[2]} source={x[3]} updated={x[4]} sourceUpdated={x[5]} icon={x[6]} tone={x[7]} href={x[8]}/>)}</div></section>
      <section className="rounded-[10px] border border-[#d4e2f0] bg-white p-2.5"><div className="mb-2 flex items-center justify-between"><h2 className="text-[14px] font-black text-[#0b2c61]">2. Tự do tài chính — Mục tiêu & Tiến độ</h2><a href="#financial-freedom-targets" className="rounded-md bg-[#0874eb] px-3 py-2 text-[9px] font-bold text-white">▣ Thiết lập mục tiêu</a></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-[9px]"><thead className="bg-[#edf3f9] text-[#365779]"><tr>{["KPI","Mục tiêu cuối","Mục tiêu tháng","Hiện tại","Khoảng cách","Tiến độ","Xu hướng","Trạng thái"].map(h=><th className="px-2 py-2 text-left font-black" key={h}>{h}</th>)}</tr></thead><tbody>{primary.map(m=><tr className="border-t border-[#e0e9f2]" key={m.code}><td className="px-2 py-2 font-bold text-[#173d68]"><a className="hover:text-[#0874eb] hover:underline" href={`/personal-finance?kpi=${m.code}#financial-freedom`}>{m.label}</a></td><td>{money(m.longTarget)}</td><td>{money(m.monthTarget)}</td><td className="font-black text-[#173d68]">{money(m.actual)}</td><td className={m.gap&&m.gap>0?"font-bold text-[#ef3c3c]":"font-bold text-[#15924a]"}>{m.gap===null?"—":money(m.gap)}</td><td><div className="flex items-center gap-2"><div className="h-2 w-[58px] overflow-hidden rounded-full bg-[#e6edf5]"><div className="h-full rounded-full bg-[#1478ee]" style={{width:`${Math.max(0,Math.min(100,m.progress??0))}%`}}/></div><span>{m.progress===null?"—":`${Math.round(m.progress)}%`}</span></div></td><td className={`text-[16px] font-black ${trendClass(m.trend)}`}>{trendVi(m.trend)}</td><td><span className={`rounded-md px-2 py-1 text-[8px] font-black ${statusClass(m.status)}`}>{statusVi(m.status)}</span></td></tr>)}</tbody></table></div>
      </section>
    </div>
    {p.cutover ? <section className="rounded-[10px] border border-[#d4e2f0] bg-white p-4"><div className="flex items-center justify-between"><div><h2 className="text-[14px] font-black text-[#0b2c61]">Nợ & Hạn mức tín dụng — Opening 30/09/2026</h2><p className="mt-1 text-[9px] text-[#7185a3]">Used principal là nợ; available credit không phải tài sản. Lãi bên dưới chỉ là planning estimate, Actual theo sao kê ngân hàng.</p></div><span className="rounded-md bg-[#edf4ff] px-2 py-1 text-[8px] font-bold text-[#3475c5]">CUTOVER</span></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] text-[9px]"><thead className="bg-[#edf3f9] text-[#365779]"><tr>{["Facility","Phân loại","Used principal","Available credit","Rate","Lãi/tháng ước tính","Maturity","Trạng thái"].map(h=><th key={h} className="px-2 py-2 text-left font-black">{h}</th>)}</tr></thead><tbody>{((p.cutover.facilities as Row[] | undefined) ?? []).map((f,i)=><tr key={i} className="border-t"><td className="px-2 py-2 font-bold text-[#173d68]">{String(f.code??"—")}</td><td>{String(f.classification??"—")}</td><td>{money(f.usedPrincipal)}</td><td>{money(f.availableCredit)}</td><td>{num(f.rate)==null?"—":`${(Number(f.rate)*100).toFixed(2)}%`}</td><td>{money(f.projectedMonthlyInterest)}</td><td>{dateVi(f.maturity)}</td><td><span className={`rounded-md px-2 py-1 text-[8px] font-bold ${statusClass(String(f.verificationStatus??"NEED_VERIFY"))}`}>{String(f.verificationStatus??"NEED_VERIFY")}</span></td></tr>)}</tbody></table></div><div className="mt-3 grid grid-cols-1 gap-2 md:grid-cols-3"><div className="rounded-lg bg-[#f6f9fd] p-3"><div className="text-[8px] font-bold text-[#7890ad]">Known bank/cash balance</div><div className="mt-1 text-[12px] font-black text-[#173d68]">{money(p.cutover.knownCash)}</div></div><div className="rounded-lg bg-[#fff8e8] p-3"><div className="text-[8px] font-bold text-[#9b752c]">Ownership chưa phân loại</div><div className="mt-1 text-[12px] font-black text-[#8b6100]">{String(p.cutover.unclassifiedCashCount??0)} account</div></div><div className="rounded-lg bg-[#f6f9fd] p-3"><div className="text-[8px] font-bold text-[#7890ad]">Net Opening Liquidity</div><div className="mt-1 text-[12px] font-black text-[#173d68]">{p.cutover.netOpeningLiquidity==null?"CẦN XÁC MINH":money(p.cutover.netOpeningLiquidity)}</div></div></div></section> : null}
    {selected?<section className="rounded-[10px] border border-[#bcd4ef] bg-[#f8fbff] p-4"><div className="flex justify-between"><div><h3 className="text-[13px] font-black text-[#102d5f]">Chi tiết KPI — {selected.label}</h3><p className="mt-1 text-[9px] text-[#68809f]">Không phải số hộp đen: hiển thị target, actual, calculation, trend và nguồn.</p></div><a href="/personal-finance#financial-freedom" className="text-[10px] font-bold text-[#0874eb]">Đóng</a></div><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-7">{[["Mục tiêu dài hạn",money(selected.longTarget)],["Mục tiêu năm",money(selected.annualTarget)],["Mục tiêu tháng",money(selected.monthTarget)],["Actual",money(selected.actual)],["Tháng trước",money(selected.prev)],["Gap",selected.gap===null?"—":money(selected.gap)],["Trend",`${trendVi(selected.trend)} ${selected.changePct===null?"":`${selected.changePct.toFixed(1)}%`}`]].map(x=><div key={x[0]} className="rounded-lg border bg-white p-3"><div className="text-[8px] font-bold text-[#7288a7]">{x[0]}</div><div className="mt-1 text-[12px] font-black text-[#173d68]">{x[1]}</div></div>)}</div><div className="mt-3 text-[9px] text-[#5d7393]">Nguồn Actual: Personal Finance canonical runtime · Historical: Monthly KPI snapshots · Target: Personal Finance Goals. {selected.code==="DEBT_SERVICE_COVERAGE"||selected.code==="SAVINGS_RATE"?"Business rule chưa được Owner phê duyệt → NEED VERIFY.":"Direction rule đã cố định theo loại KPI, không dùng quy tắc số tăng luôn tốt."}</div></section>:null}
    <div className="grid grid-cols-1 gap-3 xl:grid-cols-3"><LineChart title="Tài sản ròng 12 tháng" kpi="NET_WORTH" snapshots={p.snapshots} tone="blue"/><LineChart title="Tổng nợ 12 tháng" kpi="TOTAL_DEBT" snapshots={p.snapshots} tone="red"/><IncomeExpenseChart history={p.historyTransactions}/></div>
    <div className="grid grid-cols-1 gap-3 2xl:grid-cols-[1.2fr_.9fr]">
      <section className="rounded-[10px] border border-[#d4e2f0] bg-white p-3"><h2 className="text-[14px] font-black text-[#0b2c61]">4. Việc cần làm tháng này</h2><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[760px] text-[9px]"><thead className="bg-[#edf3f9] text-[#3b5877]"><tr>{["#","KPI","Khoảng cách","Hành động đề xuất","Hạn hoàn thành","Trạng thái"].map(h=><th key={h} className="px-2 py-2 text-left">{h}</th>)}</tr></thead><tbody>{primary.slice(0,5).map((m,i)=><tr key={m.code} className="border-t"><td className="p-2">{i+1}</td><td className="font-bold text-[#234c72]">{m.label}</td><td className={m.gap&&m.gap>0?"font-bold text-[#ef3c3c]":"text-[#169b50]"}>{m.gap===null?"—":money(m.gap)}</td><td>{actionText[m.code]??"Bổ sung dữ liệu/target và xác minh KPI"}</td><td>{dateVi(due)}</td><td><span className={`rounded-md px-2 py-1 text-[8px] font-bold ${m.status==="ACHIEVED"?"bg-[#dff8e9] text-[#15924a]":"bg-[#e7f2ff] text-[#2473c9]"}`}>{m.status==="ACHIEVED"?"Đã đạt":"Chưa bắt đầu"}</span></td></tr>)}</tbody></table></div></section>
      <section className="rounded-[10px] border border-[#d4e2f0] bg-white p-3"><h2 className="text-[14px] font-black text-[#0b2c61]">5. Nhập / cập nhật dữ liệu</h2><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">{[["↕","+ Giao dịch","Thêm giao dịch thu chi, chuyển khoản...","#input-transaction"],["▣","+ Tài khoản / cập nhật số dư","Cập nhật số dư tài khoản, thẻ, ví...","#input-account"],["▤","+ Khoản nợ / cập nhật dư nợ","Cập nhật dư nợ vay, thẻ tín dụng...","#input-debt"],["⌂","+ Tài sản / cập nhật giá trị","Cập nhật giá trị bất động sản, đầu tư...","#input-asset"]].map(x=><a href={x[3]} key={x[1]} className="flex min-h-[68px] items-center gap-3 rounded-[9px] border border-[#d9e5f1] p-3 hover:bg-[#f7fbff]"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#eef5ff] text-[20px] font-black text-[#0874eb]">{x[0]}</span><span><b className="text-[10px] text-[#173d68]">{x[1]}</b><span className="mt-1 block text-[8px] text-[#7b8da8]">{x[2]}</span></span><span className="ml-auto text-[#173d68]">›</span></a>)}</div></section>
    </div>
    <section className="rounded-[10px] border border-[#d4e2f0] bg-white p-3"><div className="flex items-center justify-between"><h2 className="text-[14px] font-black text-[#0b2c61]">6. Giao dịch gần đây</h2><a href="#data-list" className="text-[9px] font-bold text-[#0874eb]">Xem tất cả →</a></div><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[880px] text-[9px]"><thead className="bg-[#edf3f9] text-[#3b5877]"><tr>{["Ngày","Loại","Danh mục","Mô tả","Số tiền","Tài khoản","Trạng thái","Nguồn"].map(h=><th key={h} className="px-2 py-2 text-left">{h}</th>)}</tr></thead><tbody>{p.transactions.slice(0,6).map((x,i)=><tr key={String(x.id??i)} className="border-t"><td className="p-2">{dateVi(x.transaction_date)}</td><td>{String(x.transaction_type??"—")}</td><td>{String(x.category??"—")}</td><td>{String(x.description??"—")}</td><td className={x.transaction_type==="INCOME"?"font-bold text-[#12a150]":"font-bold text-[#ef3c3c]"}>{x.transaction_type==="INCOME"?"+":"-"}{money(x.amount)}</td><td>{String(x.account_id??"—")}</td><td><span className={`rounded-md px-2 py-1 text-[8px] font-bold ${statusClass(String(x.verification_status))}`}>{x.verification_status==="VERIFIED"?"ĐÃ XÁC NHẬN":"CẦN XÁC MINH"}</span></td><td>{String(x.source??"—")}</td></tr>)}{!p.transactions.length?<tr><td colSpan={8} className="p-6 text-center text-[#8493a8]">CHƯA CÓ DỮ LIỆU</td></tr>:null}</tbody></table></div></section>
    <section className="rounded-[10px] border border-[#d4e2f0] bg-white p-4"><div className="flex items-center justify-between"><div><h2 className="text-[14px] font-black text-[#0b2c61]">7. Hành trình Tự do tài chính</h2><p className="mt-1 text-[9px] text-[#7185a3]">Không có Financial Freedom Score. Mỗi giai đoạn chỉ PASS khi condition có evidence đủ.</p></div><span className="rounded-md bg-[#edf4ff] px-2 py-1 text-[8px] font-bold text-[#3475c5]">6 GIAI ĐOẠN</span></div><div className="mt-3 grid grid-cols-1 gap-2 md:grid-cols-3 xl:grid-cols-6">{(()=>{const by=(c:string)=>metrics.find(m=>m.code===c); const nw=by("NET_WORTH"),debt=by("TOTAL_DEBT"),cf=by("NET_CASH_FLOW"),ef=by("EMERGENCY_FUND"),si=by("SUSTAINABLE_INCOME"); const generalGoal=p.goals.find(x=>x.goal_type==="FINANCIAL_FREEDOM"&&!x.kpi_code&&x.status==="ACTIVE"); const stages=[
      ["1. Ổn định dòng tiền",cf?.monthTarget,cf?.actual,"Dòng tiền ròng VERIFIED và đạt target tháng",cf?.status==="ACHIEVED"?"ACHIEVED":"NEED_VERIFY"],
      ["2. Quỹ dự phòng",ef?.longTarget??ef?.monthTarget,ef?.actual,`Đạt target quỹ; coverage hiện ${num(p.position?.emergency_fund_coverage_months)?.toFixed(1)??"—"} tháng`,ef?.status==="ACHIEVED"?"ACHIEVED":"NEED_VERIFY"],
      ["3. Giảm nợ",debt?.longTarget??debt?.monthTarget,debt?.actual,"Dư nợ VERIFIED ≤ target",debt?.status==="ACHIEVED"?"ACHIEVED":"NEED_VERIFY"],
      ["4. Tài sản ròng tăng bền vững",nw?.longTarget??nw?.monthTarget,nw?.actual,"Net Worth VERIFIED và trend cải thiện",nw?.status==="ACHIEVED"&&nw?.trend==="IMPROVING"?"ACHIEVED":"NEED_VERIFY"],
      ["5. Thu nhập bền vững",si?.longTarget??si?.monthTarget,si?.actual,"Sustainable Personal Income VERIFIED ≥ target",si?.status==="ACHIEVED"?"ACHIEVED":"NEED_VERIFY"],
      ["6. Điều kiện Tự do tài chính",num(generalGoal?.target_amount),null,"Owner-approved Financial Freedom condition; chưa tự suy từ một score",generalGoal?.verification_status==="VERIFIED"?"NEED_VERIFY":"NO_DATA"],
    ]; return stages.map((st,i)=><div key={i} className="rounded-lg border border-[#dce7f2] bg-[#f9fbfe] p-3"><div className="text-[9px] font-black leading-4 text-[#173d68]">{st[0] as string}</div><div className="mt-2 text-[8px] text-[#7185a3]">Target</div><div className="text-[11px] font-black text-[#173d68]">{money(st[1])}</div><div className="mt-2 text-[8px] text-[#7185a3]">Actual</div><div className="text-[11px] font-black text-[#173d68]">{money(st[2])}</div><div className="mt-2 min-h-[34px] text-[8px] leading-3 text-[#637a99]">{st[3] as string}</div><span className={`mt-2 inline-block rounded px-2 py-1 text-[8px] font-black ${statusClass(st[4] as string)}`}>{statusVi(st[4] as string)}</span></div>);})()}</div></section>
    <details className="rounded-[10px] border border-[#d4e2f0] bg-white p-4"><summary className="cursor-pointer text-[13px] font-black text-[#102d5f]">8. Monthly Financial Review — {p.month.slice(0,7)}</summary><div className="mt-3 grid grid-cols-1 gap-2 md:grid-cols-2 xl:grid-cols-4">{(()=>{const achieved=primary.filter(m=>m.status==="ACHIEVED");const worsening=primary.filter(m=>m.trend==="WORSENING");const missing=primary.filter(m=>m.status==="NO_DATA"||m.status==="NEED_VERIFY");const nw=metrics.find(m=>m.code==="NET_WORTH"),debt=metrics.find(m=>m.code==="TOTAL_DEBT"),cf=metrics.find(m=>m.code==="NET_CASH_FLOW"),ef=metrics.find(m=>m.code==="EMERGENCY_FUND"),si=metrics.find(m=>m.code==="SUSTAINABLE_INCOME");return [
      ["KPI đạt",achieved.length?achieved.map(x=>x.label).join(", "):"Chưa có KPI đủ rule/evidence để xác nhận đạt"],
      ["KPI xấu đi",worsening.length?worsening.map(x=>x.label).join(", "):"Không có hoặc chưa đủ lịch sử"],
      ["Net Worth",`${money(nw?.actual)} · MoM ${nw?.changePct==null?"—":nw.changePct.toFixed(1)+"%"}`],
      ["Debt",`${money(debt?.actual)} · MoM ${debt?.changePct==null?"—":debt.changePct.toFixed(1)+"%"}`],
      ["Cashflow",money(cf?.actual)],["Emergency Fund",`${money(ef?.actual)} · coverage ${num(p.position?.emergency_fund_coverage_months)?.toFixed(1)??"—"} tháng`],["Sustainable Income",money(si?.actual)],["Data gaps",missing.length?missing.map(x=>x.label).join(", "):"Không còn data gap trong KPI chính"],
    ].map(x=><div key={x[0]} className="rounded-lg bg-[#f6f9fd] p-3"><div className="text-[8px] font-bold text-[#7890ad]">{x[0]}</div><div className="mt-1 text-[10px] font-semibold leading-4 text-[#173d68]">{x[1]}</div></div>)})()}</div><p className="mt-3 text-[9px] text-[#6f829e]">Target tháng mới chỉ được thay đổi qua Personal Finance Goals và Owner approval. Hệ thống không tự thay đổi target đáng kể.</p></details>
    <details id="financial-freedom-targets" className="rounded-[10px] border border-[#bcd4ef] bg-white p-4"><summary className="cursor-pointer text-[13px] font-black text-[#102d5f]">Thiết lập mục tiêu Financial Freedom</summary><p className="mt-2 text-[9px] text-[#7185a3]">Targets lưu trong Personal Finance Goals; Owner approval tại form này được lưu evidence + audit. Không sửa Monthly Target của tháng đã kết thúc.</p><div className="mt-3 grid grid-cols-1 gap-3 xl:grid-cols-3">{FREEDOM_KPIS.map(k=><form action={saveFinancialFreedomTarget} key={k.code} className="grid grid-cols-2 gap-2 rounded-lg bg-[#f6f9fd] p-3"><input type="hidden" name="kpi_code" value={k.code}/><b className="col-span-2 text-[10px] text-[#173d68]">{k.label}</b><select name="target_level" className="rounded border p-2 text-[9px]" defaultValue="MONTHLY"><option>MONTHLY</option><option>ANNUAL</option><option>LONG_TERM</option></select><input name="target_amount" className="rounded border p-2 text-[9px]" inputMode="decimal" placeholder="Giá trị mục tiêu" required/><input name="target_period" type="month" defaultValue={p.month.slice(0,7)} className="rounded border p-2 text-[9px]"/><input name="target_year" type="number" defaultValue={p.month.slice(0,4)} className="rounded border p-2 text-[9px]"/><input name="reason" className="col-span-2 rounded border p-2 text-[9px]" placeholder="Lý do / quyết định mục tiêu" required/><button className="col-span-2 rounded bg-[#0874eb] px-3 py-2 text-[9px] font-bold text-white" disabled={p.migrationMissing}>Lưu mục tiêu (Owner approved)</button></form>)}</div></details>
  </div>;
}
