import { FREEDOM_KPIS, canonicalKpiStatus, gapToTarget, kpiTrend, targetProgress, type FreedomKpiCode } from "@/server/finance/financial-freedom-core";

type Row=Record<string,unknown>;
type Props={month:string;operating:Row|null;position:Row|null;monthly:Row|null;goals:Row[];snapshots:Row[];transactions:Row[];historyTransactions:Row[];debts:Row[];personalAccounts:Row[];transfers:Row[];migrationMissing:boolean};
const nf=new Intl.NumberFormat("vi-VN",{maximumFractionDigits:0});
const money=(v:unknown)=>v===null||v===undefined||v===""?"—":Number.isFinite(Number(v))?`${nf.format(Number(v))} đ`:"—";
const num=(v:unknown)=>v===null||v===undefined||v===""?null:Number.isFinite(Number(v))?Number(v):null;
const pct=(v:unknown)=>num(v)===null?"—":`${Math.round(Number(v))}%`;
function badge(status:string){const s=status.toUpperCase();if(["VERIFIED","MATCHED","ACHIEVED","ON_TRACK","PASS"].includes(s))return "bg-emerald-100 text-emerald-700";if(["AT_RISK","NEED_VERIFY","STALE"].includes(s))return "bg-amber-100 text-amber-700";if(["HOLD","OFF_TRACK","VARIANCE"].includes(s))return "bg-rose-100 text-rose-700";return "bg-slate-100 text-slate-600"}
function statusVi(status:string){return ({VERIFIED:"Đã xác minh",MATCHED:"Khớp",ACHIEVED:"Đã đạt",ON_TRACK:"Đúng tiến độ",PASS:"PASS",AT_RISK:"Cần chú ý",NEED_VERIFY:"Cần xác minh",STALE:"Dữ liệu cũ",HOLD:"HOLD",OFF_TRACK:"Chậm tiến độ",VARIANCE:"Cần đối soát",NO_DATA:"Chưa có dữ liệu"} as Record<string,string>)[status]??status}
function Icon({kind}:{kind:string}){const c="h-5 w-5";if(kind==="wallet")return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 6h14a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h12"/><path d="M16 11h6v4h-6a2 2 0 1 1 0-4Z"/></svg>;if(kind==="shield")return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 3 5 6v5c0 4.6 2.9 8.4 7 10 4.1-1.6 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></svg>;return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 19V9m5 10V5m5 14v-7m5 7V3"/></svg>}
function Card({label,value,note,status,kind,tone}:{label:string;value:string;note:string;status:string;kind:string;tone:string}){return <div className="rounded-[10px] border border-[#d7e4f1] bg-white p-3 shadow-[0_1px_3px_rgba(15,45,80,.05)]"><div className="flex gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${tone}`}><Icon kind={kind}/></div><div className="min-w-0 flex-1"><div className="text-[10px] font-bold text-[#395779]">{label}</div><div className="mt-1 truncate text-[18px] font-black tracking-tight text-[#0e2b5d]">{value}</div><div className="mt-1 text-[8px] text-[#8496af]">{note}</div><span className={`mt-2 inline-block rounded-md px-2 py-1 text-[8px] font-black ${badge(status)}`}>{statusVi(status)}</span></div></div></div>}
function targetFor(goals:Row[],code:string,level:string,month:string){return goals.filter(g=>g.kpi_code===code&&g.target_level===level&&g.status==="ACTIVE"&&g.verification_status==="VERIFIED").filter(g=>level!=="MONTHLY"||String(g.target_period).slice(0,7)===month.slice(0,7)).filter(g=>level!=="ANNUAL"||Number(g.target_year)===Number(month.slice(0,4))).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))[0]}
function Bars({rows,month}:{rows:Row[];month:string}){const now=new Date(`${month}T00:00:00Z`);const ms=Array.from({length:6},(_,i)=>{const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-5+i,1));return d.toISOString().slice(0,7)});const data=ms.map(m=>{const rr=rows.filter(x=>String(x.transaction_date??"").startsWith(m)&&x.record_status==="ACTIVE"&&x.verification_status==="VERIFIED");return {m,inc:rr.filter(x=>x.transaction_type==="INCOME").reduce((s,x)=>s+Number(x.amount??0),0),exp:rr.filter(x=>x.transaction_type==="EXPENSE").reduce((s,x)=>s+Number(x.amount??0),0)}});const max=Math.max(1,...data.flatMap(x=>[x.inc,x.exp]));return <section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><div className="flex justify-between"><h3 className="text-[12px] font-black text-[#102d5f]">Thu nhập và chi phí — 6 tháng</h3><span className="text-[8px] text-[#7388a7]"><b className="text-[#1679ef]">●</b> Thu nhập &nbsp; <b className="text-[#ff7e45]">●</b> Chi phí</span></div><div className="mt-4 flex h-[140px] items-end gap-5 border-b border-[#dce6f1] px-2">{data.map(x=><div key={x.m} className="flex h-full flex-1 items-end justify-center gap-1"><div className="w-[34%] rounded-t bg-[#1679ef]" style={{height:`${x.inc?Math.max(4,x.inc/max*100):0}%`}}/><div className="w-[34%] rounded-t bg-[#ff7e45]" style={{height:`${x.exp?Math.max(4,x.exp/max*100):0}%`}}/></div>)}</div><div className="mt-2 flex justify-between text-[8px] text-[#7488a7]">{ms.map(m=><span key={m}>Th{Number(m.slice(5,7))}</span>)}</div></section>}

export function PersonalFinanceOperatingDashboard(p:Props){
 const summary=(p.operating?.summary??{}) as Row;
 const personalOperatingAccount=p.personalAccounts.find(x=>String(x.external_key??"")==="TPBANK-501"||String(x.name??"").includes("501"));
 const safetyAccount=p.personalAccounts.find(x=>x.is_emergency_fund===true);
 const accountStatus=(row:Row|undefined)=>{if(!row||row.verification_status!=="VERIFIED")return "NEED_VERIFY";const asOf=String(row.balance_as_of??"");if(asOf&&asOf.slice(0,7)<p.month.slice(0,7))return "STALE";return "VERIFIED"};
 const personalCash=num(personalOperatingAccount?.current_balance);
 const emergency=num(safetyAccount?.current_balance);
 const cf=num(p.monthly?.personal_net_cash_flow);
 const totalDebt=num(p.position?.verified_liabilities);
 const netWorth=num(p.position?.net_worth);
 const monthExpenses=p.transactions.filter(x=>x.transaction_type==="EXPENSE"&&x.verification_status==="VERIFIED").reduce((s,x)=>s+Number(x.amount??0),0);
 const hasExpenseData=p.transactions.some(x=>x.transaction_type==="EXPENSE"&&x.verification_status==="VERIFIED");
 const businessToPersonal=p.transfers.filter(x=>x.direction==="BUSINESS_TO_PERSONAL"&&x.verification_status==="VERIFIED").reduce((s,x)=>s+Number(x.amount??0),0);
 const hasBridgeData=p.transfers.some(x=>x.direction==="BUSINESS_TO_PERSONAL"&&x.verification_status==="VERIFIED");
 const distributable=num(summary.ownerDistributableCash);
 const cards=[
  ["Tiền cá nhân khả dụng",money(personalCash),"TPBank 501 · chi tiêu cá nhân/gia đình",accountStatus(personalOperatingAccount),"wallet","bg-blue-50 text-blue-600"],
  ["Quỹ an toàn",money(emergency),"TPBank TKTK_A01 · không dùng chi tiêu hằng ngày",accountStatus(safetyAccount),"shield","bg-emerald-50 text-emerald-600"],
  ["Tổng nợ",money(totalDebt),"Nghĩa vụ nợ cá nhân đã xác minh",totalDebt!==null?"VERIFIED":"NEED_VERIFY","wallet","bg-rose-50 text-rose-600"],
  ["Tài sản ròng",money(netWorth),"Tài sản đã xác minh trừ nghĩa vụ nợ",netWorth!==null?"VERIFIED":"NEED_VERIFY","chart","bg-violet-50 text-violet-600"],
  ["Dòng tiền tháng",money(cf),"Thu cá nhân trừ chi cá nhân trong kỳ",cf!==null?"VERIFIED":"NO_DATA","chart","bg-blue-50 text-blue-600"],
  ["Chi gia đình tháng",hasExpenseData?money(monthExpenses):"—","Tổng giao dịch EXPENSE đã xác minh",hasExpenseData?"VERIFIED":"NO_DATA","wallet","bg-amber-50 text-amber-600"],
 ] as const;
 const missingCritical=[personalCash===null,totalDebt===null,cf===null].filter(Boolean).length;
 const healthLabel=missingCritical>0?"CHƯA ĐỦ DỮ LIỆU ĐỂ CHẤM ĐIỂM TỔNG THỂ":emergency===0?"CẦN CỦNG CỐ QUỸ AN TOÀN":"ĐỦ DỮ LIỆU ĐÁNH GIÁ";
 const metricActual=(code:string)=>code==="TOTAL_DEBT"?totalDebt:code==="NET_CASH_FLOW"?cf:code==="EMERGENCY_FUND"?emergency:code==="NET_WORTH"?netWorth:code==="SUSTAINABLE_INCOME"?p.transactions.filter(x=>x.transaction_type==="INCOME"&&x.is_sustainable_income===true&&x.verification_status==="VERIFIED").reduce((s,x)=>s+Number(x.amount??0),0)||null:null;
 const kpCodes=["NET_WORTH","TOTAL_DEBT","EMERGENCY_FUND","NET_CASH_FLOW","SUSTAINABLE_INCOME"] as FreedomKpiCode[];
 const kpis=kpCodes.map(code=>{const def=FREEDOM_KPIS.find(x=>x.code===code)!;const target=num(targetFor(p.goals,code,"MONTHLY",p.month)?.target_amount)??num(targetFor(p.goals,code,"ANNUAL",p.month)?.target_amount)??num(targetFor(p.goals,code,"LONG_TERM",p.month)?.target_amount);const actual=metricActual(code);const prev=num(p.snapshots.filter(x=>x.kpi_code===code).sort((a,b)=>String(b.period).localeCompare(String(a.period)))[0]?.actual_value);const progress=targetProgress({actual,target,direction:def.direction});return {code,label:def.label,target,actual,gap:gapToTarget(actual,target,def.direction),progress,status:canonicalKpiStatus({actual,target,direction:def.direction,verified:actual!==null}),trend:kpiTrend(actual,prev,def.direction)}});
 return <div className="space-y-3 text-[#17233d] [color-scheme:light]">
  {p.migrationMissing?<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-[10px] font-bold text-amber-800">HOLD: Personal Finance schema chưa PASS.</div>:null}
  <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 xl:grid-cols-3">{cards.map((c,i)=><Card key={i} label={c[0]} value={c[1]} note={c[2]} status={c[3]} kind={c[4]} tone={c[5]}/>)}</div>

  <section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><h2 className="text-[13px] font-black text-[#102d5f]">Sức khỏe tài chính cá nhân</h2><p className="mt-1 text-[9px] text-[#7488a5]">Chỉ đánh giá dữ liệu cá nhân; thiếu dữ liệu quan trọng thì fail closed.</p></div><span className={`rounded-md px-3 py-2 text-[9px] font-black ${missingCritical>0?"bg-amber-100 text-amber-700":emergency===0?"bg-rose-100 text-rose-700":"bg-emerald-100 text-emerald-700"}`}>{healthLabel}</span></div><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-5">{[["Thanh khoản",personalCash,accountStatus(personalOperatingAccount)],["Quỹ an toàn",emergency,emergency===0&&accountStatus(safetyAccount)==="VERIFIED"?"HOLD":accountStatus(safetyAccount)],["Tổng nợ",totalDebt,totalDebt!==null&&totalDebt>0?"AT_RISK":totalDebt===0?"VERIFIED":"NEED_VERIFY"],["Dòng tiền tháng",cf,cf!==null?"VERIFIED":"NO_DATA"],["Tài sản ròng",netWorth,netWorth!==null?"VERIFIED":"NO_DATA"]].map(([label,value,status])=><div key={label as string} className="rounded-lg bg-[#f7faff] p-3"><div className="text-[8px] font-bold text-[#667f9f]">{label as string}</div><div className="mt-1 text-[12px] font-black text-[#17355f]">{money(value)}</div><span className={`mt-2 inline-block rounded px-2 py-1 text-[7px] font-bold ${badge(String(status))}`}>{statusVi(String(status))}</span></div>)}</div></section>

  <div className="grid grid-cols-1 gap-2 xl:grid-cols-[.8fr_1.2fr]">
   <section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><div className="flex items-center justify-between"><div><h2 className="text-[13px] font-black text-[#102d5f]">Kinh doanh → Cá nhân</h2><p className="mt-1 text-[9px] text-[#7488a5]">Chỉ hiển thị dòng tiền thực sự chuyển sang cá nhân; không đưa P&L/OTA/AP kinh doanh vào đây.</p></div><a href="/finance" className="rounded-md bg-[#eef6ff] px-3 py-2 text-[9px] font-black text-[#1768df]">Xem Tài chính kinh doanh →</a></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg bg-[#f7faff] p-3"><div className="text-[8px] font-bold text-[#667f9f]">Đã chuyển sang cá nhân tháng này</div><div className="mt-1 text-[15px] font-black text-[#17355f]">{hasBridgeData?money(businessToPersonal):"—"}</div><span className={`mt-2 inline-block rounded px-2 py-1 text-[7px] font-bold ${badge(hasBridgeData?"VERIFIED":"NO_DATA")}`}>{statusVi(hasBridgeData?"VERIFIED":"NO_DATA")}</span></div><div className="rounded-lg bg-[#f7faff] p-3"><div className="text-[8px] font-bold text-[#667f9f]">Có thể phân phối từ kinh doanh</div><div className="mt-1 text-[15px] font-black text-[#17355f]">{money(distributable)}</div><span className={`mt-2 inline-block rounded px-2 py-1 text-[7px] font-bold ${badge(distributable!==null?"VERIFIED":"HOLD")}`}>{statusVi(distributable!==null?"VERIFIED":"HOLD")}</span></div></div></section>
   <Bars rows={p.historyTransactions} month={p.month}/>
  </div>

  <details className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><summary className="cursor-pointer text-[12px] font-black text-[#102d5f]">Mục tiêu tự do tài chính · xem chi tiết</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[700px] text-[9px]"><thead className="bg-[#edf3f8] text-[#48627f]"><tr>{["KPI","Mục tiêu","Hiện tại","Khoảng cách","Tiến độ","Trạng thái"].map(h=><th key={h} className="px-2 py-2 text-left font-black">{h}</th>)}</tr></thead><tbody>{kpis.map(k=><tr key={k.code} className="border-t border-[#e3ebf3]"><td className="px-2 py-2 font-bold text-[#183b68]">{k.label}</td><td>{money(k.target)}</td><td className="font-bold">{money(k.actual)}</td><td>{k.gap===null?"—":money(k.gap)}</td><td>{pct(k.progress)}</td><td><span className={`rounded-md px-2 py-1 text-[8px] font-bold ${badge(k.status)}`}>{statusVi(k.status)}</span></td></tr>)}</tbody></table></div></details>
 </div>
}
