import { approveFinanceAllocationProposal, prepareFinanceTransfer, saveFinanceAllocationDraft } from "./finance-actions";
import { FREEDOM_KPIS, canonicalKpiStatus, gapToTarget, kpiTrend, targetProgress, type FreedomKpiCode } from "@/server/finance/financial-freedom-core";

type Row=Record<string,unknown>;
type Props={month:string;operating:Row|null;position:Row|null;monthly:Row|null;goals:Row[];snapshots:Row[];transactions:Row[];historyTransactions:Row[];debts:Row[];migrationMissing:boolean};
const nf=new Intl.NumberFormat("vi-VN",{maximumFractionDigits:0});
const money=(v:unknown)=>v===null||v===undefined||v===""?"—":Number.isFinite(Number(v))?`${nf.format(Number(v))} đ`:"—";
const num=(v:unknown)=>v===null||v===undefined||v===""?null:Number.isFinite(Number(v))?Number(v):null;
const pct=(v:unknown)=>num(v)===null?"—":`${Math.round(Number(v))}%`;
const viDate=(v:unknown)=>{if(!v)return"—";const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"Asia/Ho_Chi_Minh"}).format(d)};
function badge(status:string){const s=status.toUpperCase();if(["VERIFIED","MATCHED","ACHIEVED","ON_TRACK","PASS"].includes(s))return "bg-emerald-100 text-emerald-700";if(["AT_RISK","NEED_VERIFY","STALE"].includes(s))return "bg-amber-100 text-amber-700";if(["HOLD","OFF_TRACK","VARIANCE"].includes(s))return "bg-rose-100 text-rose-700";return "bg-slate-100 text-slate-600"}
function statusVi(status:string){return ({VERIFIED:"Đúng tiến độ",MATCHED:"Khớp",ACHIEVED:"Đã đạt",ON_TRACK:"Đúng tiến độ",PASS:"PASS",AT_RISK:"Cần chú ý",NEED_VERIFY:"Cần xác minh",STALE:"Dữ liệu cũ",HOLD:"Cần xác minh",OFF_TRACK:"Chậm tiến độ",VARIANCE:"Cần đối soát",NO_DATA:"Chưa có dữ liệu"} as Record<string,string>)[status]??status}
function Icon({kind}:{kind:string}){const c="h-5 w-5";if(kind==="wallet")return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 6h14a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h12"/><path d="M16 11h6v4h-6a2 2 0 1 1 0-4Z"/></svg>;if(kind==="shield")return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 3 5 6v5c0 4.6 2.9 8.4 7 10 4.1-1.6 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></svg>;if(kind==="plane")return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m22 2-7 20-4-9-9-4 20-7Z"/></svg>;if(kind==="refresh")return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20 6v5h-5M4 18v-5h5"/><path d="M6 9a7 7 0 0 1 12-2l2 4M18 15a7 7 0 0 1-12 2l-2-4"/></svg>;return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 19V9m5 10V5m5 14v-7m5 7V3"/></svg>}
function Card({label,value,note,status,kind,tone,trend}:{label:string;value:string;note:string;status:string;kind:string;tone:string;trend?:string}){return <div className="rounded-[10px] border border-[#d7e4f1] bg-white p-3 shadow-[0_1px_3px_rgba(15,45,80,.05)]"><div className="flex gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${tone}`}><Icon kind={kind}/></div><div className="min-w-0 flex-1"><div className="text-[10px] font-bold text-[#395779]">{label}</div><div className="mt-1 flex items-baseline justify-between gap-2"><div className="truncate text-[18px] font-black tracking-tight text-[#0e2b5d]">{value}</div><span className="text-[10px] font-black text-emerald-600">{trend??"—"}</span></div><div className="mt-1 text-[8px] text-[#8496af]">{note}</div><span className={`mt-2 inline-block rounded-md px-2 py-1 text-[8px] font-black ${badge(status)}`}>{statusVi(status)}</span></div></div></div>}
function targetFor(goals:Row[],code:string,level:string,month:string){return goals.filter(g=>g.kpi_code===code&&g.target_level===level&&g.status==="ACTIVE"&&g.verification_status==="VERIFIED").filter(g=>level!=="MONTHLY"||String(g.target_period).slice(0,7)===month.slice(0,7)).filter(g=>level!=="ANNUAL"||Number(g.target_year)===Number(month.slice(0,4))).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))[0]}
function MiniLine({title,rows,code}:{title:string;rows:Row[];code:string}){const d=rows.filter(x=>x.kpi_code===code&&num(x.actual_value)!==null).sort((a,b)=>String(a.period).localeCompare(String(b.period))).slice(-6);const vals=d.map(x=>Number(x.actual_value));const lo=vals.length?Math.min(...vals):0,hi=vals.length?Math.max(...vals):1,r=Math.max(1,hi-lo);const pts=d.map((x,i)=>`${24+i*(430/Math.max(1,d.length-1))},${104-((Number(x.actual_value)-lo)/r)*66}`).join(" ");return <section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><div className="flex items-start justify-between"><h3 className="text-[12px] font-black text-[#102d5f]">{title}</h3><span className="text-[8px] text-[#8295ae]">so với 6 tháng trước</span></div>{d.length?<><svg viewBox="0 0 480 125" className="mt-2 h-[145px] w-full"><path d="M20 110H465M20 75H465M20 40H465" stroke="#e2ebf4"/><polyline points={pts} fill="none" stroke="#1779ef" strokeWidth="3"/>{d.map((x,i)=>{const [cx,cy]=pts.split(" ")[i].split(",");return <g key={i}><circle cx={cx} cy={cy} r="4" fill="#1779ef"/><text x={cx} y={Number(cy)-8} textAnchor="middle" fontSize="8" fill="#1768df">{nf.format(Number(x.actual_value)/1_000_000_000)} tỷ</text></g>})}</svg><div className="flex justify-between text-[8px] text-[#7388a7]">{d.map(x=><span key={String(x.period)}>Th{Number(String(x.period).slice(5,7))}</span>)}</div></>:<div className="grid h-[165px] place-items-center text-[10px] font-semibold text-[#8999ae]">CHƯA CÓ DỮ LIỆU LỊCH SỬ</div>}</section>}
function Bars({rows}:{rows:Row[]}){const now=new Date("2026-10-01T00:00:00Z");const ms=Array.from({length:6},(_,i)=>{const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-5+i,1));return d.toISOString().slice(0,7)});const data=ms.map(m=>{const rr=rows.filter(x=>String(x.transaction_date??"").startsWith(m)&&x.record_status==="ACTIVE"&&x.verification_status==="VERIFIED");return {m,inc:rr.filter(x=>x.transaction_type==="INCOME").reduce((s,x)=>s+Number(x.amount??0),0),exp:rr.filter(x=>x.transaction_type==="EXPENSE").reduce((s,x)=>s+Number(x.amount??0),0)}});const max=Math.max(1,...data.flatMap(x=>[x.inc,x.exp]));return <section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><div className="flex justify-between"><h3 className="text-[12px] font-black text-[#102d5f]">Thu nhập vs Chi phí</h3><span className="text-[8px] text-[#7388a7]"><b className="text-[#1679ef]">●</b> Thu nhập &nbsp; <b className="text-[#ff7e45]">●</b> Chi phí</span></div><div className="mt-4 flex h-[140px] items-end gap-5 border-b border-[#dce6f1] px-2">{data.map(x=><div key={x.m} className="flex h-full flex-1 items-end justify-center gap-1"><div className="w-[34%] rounded-t bg-[#1679ef]" style={{height:`${x.inc?Math.max(4,x.inc/max*100):0}%`}}/><div className="w-[34%] rounded-t bg-[#ff7e45]" style={{height:`${x.exp?Math.max(4,x.exp/max*100):0}%`}}/></div>)}</div><div className="mt-2 flex justify-between text-[8px] text-[#7488a7]">{ms.map(m=><span key={m}>Th{Number(m.slice(5,7))}</span>)}</div></section>}

export function PersonalFinanceOperatingDashboard(p:Props){
 const summary=(p.operating?.summary??{}) as Row, accounts=(p.operating?.accounts??[]) as Row[], facilities=(p.operating?.facilities??[]) as Row[], ar=(p.operating?.ar??[]) as Row[], ap=(p.operating?.ap??[]) as Row[], pnl=(p.operating?.pnl??[]) as Row[], close=(p.operating?.closeChecklist??[]) as Row[], plan=(p.operating?.plan??[]) as Row[], allocation=(p.operating?.latestAllocation??null) as Row|null;
 const debt401=facilities.find(x=>String(x.code).includes("401")), debt407=facilities.find(x=>String(x.code).includes("407")), family=p.debts.find(x=>x.debt_type==="FAMILY");
 const ota=num(summary.otaReceivable), dist=num(summary.ownerDistributableCash), tax=num(summary.taxReserve), personalCash=num(summary.personalCash), emergency=num(summary.emergencyFund), usedDebt=num(summary.bankDebtUsed), variance=num(summary.bankBookVariance), cf=num(p.monthly?.personal_net_cash_flow);
 const cards=[
  ["Tiền cá nhân khả dụng",money(personalCash),"Tiền mặt & tiền gửi cá nhân",personalCash!==null?"VERIFIED":"NEED_VERIFY","wallet","bg-blue-50 text-blue-600"],
  ["Quỹ dự phòng",money(emergency),"Tương đương quỹ an toàn đã đối soát",emergency!==null?"VERIFIED":"NEED_VERIFY","shield","bg-emerald-50 text-emerald-600"],
  ["Nợ ngân hàng đang dùng",money(usedDebt),"Dư nợ thực tế đang dùng",usedDebt!==null?"VERIFIED":"NEED_VERIFY","wallet","bg-rose-50 text-rose-600"],
  ["Dòng tiền ròng tháng",money(cf),"Thu nhập - Chi phí (tháng 10)",cf!==null?"VERIFIED":"NEED_VERIFY","chart","bg-blue-50 text-blue-600"],
  ["TK Thuế",money(tax),"Restricted cash · không phải free cash",tax!==null?"VERIFIED":"NEED_VERIFY","shield","bg-amber-50 text-amber-600"],
  ["Tiền có thể phân phối",money(dist),"Sau thuế, công nợ, reserve & interest",dist!==null?"VERIFIED":"HOLD","chart","bg-emerald-50 text-emerald-600"],
  ["OTA chờ về",money(ota),"Business AR · Agoda / Expedia",ota!==null?"VERIFIED":"NEED_VERIFY","plane","bg-blue-50 text-blue-600"],
  ["Chênh lệch thực tế / trên sổ",money(variance),`${Number(summary.bankReconOpenCount??0)} tài khoản cần đối soát`,Number(summary.bankReconOpenCount??0)===0?"MATCHED":"NEED_VERIFY","refresh","bg-violet-50 text-violet-600"]
 ] as const;
 const metricActual=(code:string)=>code==="TOTAL_DEBT"?num(p.position?.verified_liabilities):code==="NET_CASH_FLOW"?cf:code==="EMERGENCY_FUND"?emergency:code==="NET_WORTH"?num(p.position?.net_worth):code==="SUSTAINABLE_INCOME"?p.transactions.filter(x=>x.transaction_type==="INCOME"&&x.is_sustainable_income===true&&x.verification_status==="VERIFIED").reduce((s,x)=>s+Number(x.amount??0),0)||null:null;
 const kpCodes=["NET_WORTH","TOTAL_DEBT","EMERGENCY_FUND","NET_CASH_FLOW","SUSTAINABLE_INCOME"] as FreedomKpiCode[];
 const kpis=kpCodes.map(code=>{const def=FREEDOM_KPIS.find(x=>x.code===code)!;const target=num(targetFor(p.goals,code,"MONTHLY",p.month)?.target_amount)??num(targetFor(p.goals,code,"ANNUAL",p.month)?.target_amount)??num(targetFor(p.goals,code,"LONG_TERM",p.month)?.target_amount);const actual=metricActual(code);const prev=num(p.snapshots.filter(x=>x.kpi_code===code).sort((a,b)=>String(b.period).localeCompare(String(a.period)))[0]?.actual_value);const progress=targetProgress({actual,target,direction:def.direction});return {code,label:def.label,target,actual,gap:gapToTarget(actual,target,def.direction),progress,status:canonicalKpiStatus({actual,target,direction:def.direction,verified:actual!==null}),trend:kpiTrend(actual,prev,def.direction)}});
 const ownerAdj=(allocation?.owner_adjustment??{}) as Row; const proposalId=String(allocation?.id??""); const proposalApproved=allocation?.status==="APPROVED";
 const profitBefore=num(summary.profitBeforeTax),taxProvision=num(summary.taxProvision),profitAfter=num(summary.profitAfterTax);
 return <div className="space-y-3 text-[#17233d] [color-scheme:light]">
  {p.migrationMissing?<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-[10px] font-bold text-amber-800">HOLD: Finance Operating OS migration chưa PASS.</div>:null}
  <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 xl:grid-cols-4">{cards.map((c,i)=><Card key={i} label={c[0]} value={c[1]} note={c[2]} status={c[3]} kind={c[4]} tone={c[5]}/>)}</div>
  <div className="grid grid-cols-1 gap-2 xl:grid-cols-[1.18fr_.82fr]"><section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><h2 className="text-[13px] font-black text-[#102d5f]">◎ &nbsp;Tự do tài chính — Mục tiêu & tiến độ</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[700px] text-[9px]"><thead className="bg-[#edf3f8] text-[#48627f]"><tr>{["KPI","Mục tiêu tháng","Hiện tại","Khoảng cách","Tiến độ","Trạng thái"].map(h=><th key={h} className="px-2 py-2 text-left font-black">{h}</th>)}</tr></thead><tbody>{kpis.map(k=><tr key={k.code} className="border-t border-[#e3ebf3]"><td className="px-2 py-2 font-bold text-[#183b68]">{k.label}</td><td>{money(k.target)}</td><td className="font-bold">{money(k.actual)}</td><td className={(k.gap??0)>0?"font-bold text-rose-500":"font-bold text-emerald-600"}>{k.gap===null?"—":money(k.gap)}</td><td><div className="flex items-center gap-2"><div className="h-2 w-20 overflow-hidden rounded-full bg-[#e6edf5]"><div className="h-full rounded-full bg-[#1478ee]" style={{width:`${Math.max(0,Math.min(100,k.progress??0))}%`}}/></div><span>{pct(k.progress)}</span></div></td><td><span className={`rounded-md px-2 py-1 text-[8px] font-bold ${badge(k.status)}`}>{statusVi(k.status)}</span></td></tr>)}</tbody></table></div></section><MiniLine title="Tài sản ròng 6 tháng" rows={p.snapshots} code="NET_WORTH"/></div>
  <div className="grid grid-cols-1 gap-2 xl:grid-cols-[1.18fr_.82fr]"><section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><h2 className="text-[13px] font-black text-[#102d5f]">▣ &nbsp;Phân bổ dòng tiền tháng {Number(p.month.slice(5,7))}/{p.month.slice(0,4)}</h2><p className="mt-1 text-[9px] text-[#7488a5]">Từ lợi nhuận sau thuế, phân bổ theo nguyên tắc an toàn — ưu tiên dự phòng · kiểm soát nợ · cân bằng cuộc sống.</p><div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-4">{[["Lợi nhuận trước thuế",profitBefore,"bg-blue-50 text-blue-600"],["Trích lập thuế",taxProvision,"bg-rose-50 text-rose-600"],["Lợi nhuận sau thuế",profitAfter,"bg-emerald-50 text-emerald-600"],["Tiền có thể phân phối",dist,"bg-blue-50 text-blue-600"]].map(x=><div key={x[0] as string} className="rounded-lg border border-[#e0e8f1] p-3"><div className="text-[8px] font-bold text-[#667f9f]">{x[0] as string}</div><div className="mt-1 text-[13px] font-black text-[#143463]">{money(x[1])}</div><div className={`mt-2 inline-block rounded-md px-2 py-1 text-[8px] font-bold ${x[1]===null?"bg-amber-100 text-amber-700":x[2] as string}`}>{x[1]===null?"CẦN XÁC MINH":"ĐÃ XÁC MINH"}</div></div>)}</div>
   <div className="mt-3 flex items-center justify-between"><h3 className="text-[10px] font-black text-[#1768df]">⚙ Phân bổ đề xuất / CEO điều chỉnh</h3><span className={`rounded px-2 py-1 text-[8px] font-bold ${badge(String(allocation?.verification_status??summary.distributionStatus??"HOLD"))}`}>{statusVi(String(allocation?.verification_status??summary.distributionStatus??"HOLD"))}</span></div>
   <form action={saveFinanceAllocationDraft} className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-4"><input type="hidden" name="proposal_month" value={p.month}/>{[["personal","Cá nhân"],["emergency_fund","Quỹ dự phòng"],["overdraft_401","Trả thấu chi 401"],["business_reserve","Giữ lại kinh doanh"],["tax_reserve","Thuế"],["debt_repayment","Trả nợ khác"],["other","Khác"]].map(([n,l])=><label key={n} className="rounded-lg border border-[#e0e8f1] bg-[#fbfdff] p-2 text-[8px] font-bold text-[#526c8d]">{l}<input name={n} defaultValue={Number(ownerAdj[n]??0)} inputMode="numeric" className="mt-2 w-full rounded border border-[#d3e0ee] bg-white px-2 py-2 text-[10px] font-black text-[#183d6b]" disabled={dist===null}/></label>)}<button disabled={dist===null} className="rounded-lg border border-[#bfd5f2] bg-white px-3 py-2 text-[9px] font-bold text-[#1768df] disabled:opacity-40">Lưu phương án</button></form>
   <div className="mt-3 flex gap-2"><a href="#transfer-preview" className={`rounded-md px-4 py-2 text-[9px] font-bold ${proposalApproved?"bg-[#0874eb] text-white":"pointer-events-none bg-slate-200 text-slate-500"}`}>✈ Xem trước chuyển tiền →</a>{allocation?.status==="DRAFT"?<form action={approveFinanceAllocationProposal} className="flex gap-2"><input type="hidden" name="proposal_id" value={proposalId}/><input name="confirmation" placeholder="PHÊ DUYỆT" className="w-28 rounded border bg-white px-2 text-[9px] text-[#17233d]"/><button className="rounded-md border border-[#bfd5f2] bg-white px-3 py-2 text-[9px] font-bold text-[#294d78]">Phê duyệt phương án</button></form>:null}</div>
  </section><Bars rows={p.historyTransactions}/></div>
  <div className="grid grid-cols-1 gap-2 xl:grid-cols-[1.18fr_.82fr]"><section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><h2 className="text-[13px] font-black text-[#102d5f]">▣ &nbsp;Tài khoản & số dư</h2><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[820px] text-[8px]"><thead className="bg-[#edf3f8] text-[#506987]"><tr>{["Tên tài khoản","Loại / Vai trò","Domain","Số dư thực tế","Số dư trên sổ","Chênh lệch","Trạng thái"].map(h=><th key={h} className="px-2 py-2 text-left">{h}</th>)}</tr></thead><tbody>{accounts.map(a=><tr key={String(a.code)} className="border-t"><td className="px-2 py-2 font-bold text-[#1a416e]">{String(a.name)}</td><td>{((a.roles as string[]|undefined)??[]).join(" · ")||"—"}</td><td>{String(a.domain??"—")}</td><td>{money(a.bankBalance)}</td><td>{money(a.bookBalance)}</td><td className={Number(a.variance??0)===0?"text-emerald-600":"text-rose-500"}>{money(a.variance)}</td><td><span className={`rounded px-2 py-1 font-bold ${badge(String(a.reconciliationStatus??"NEED_VERIFY"))}`}>{statusVi(String(a.reconciliationStatus??"NEED_VERIFY"))}</span></td></tr>)}</tbody></table></div></section>
   <section className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><div className="flex justify-between"><h2 className="text-[13px] font-black text-[#102d5f]">▱ &nbsp;Nợ & thấu chi</h2><a href="#finance-details" className="text-[9px] font-bold text-[#0874eb]">Xem chi tiết →</a></div><div className="mt-3 grid grid-cols-2 gap-2">{[["Dư nợ 401",debt401?.usedPrincipal,"bg-rose-50 text-rose-600",`Lãi dự kiến ${money(debt401?.projectedMonthlyInterest)}`],["Hạn mức 407",debt407?.limit,"bg-violet-50 text-violet-600","Chỉ là hạn mức dự phòng"],["Nợ người nhà",family?.current_principal,"bg-blue-50 text-blue-600",family?`${family.liability_quantity??"—"} chỉ vàng`:"—"],["Lãi dự kiến tháng",summary.projectedInterest,"bg-amber-50 text-amber-600","Actual theo sao kê ngân hàng"]].map(x=><div key={x[0] as string} className="rounded-lg border border-[#e0e8f1] p-3"><div className="text-[8px] font-bold text-[#496383]">{x[0] as string}</div><div className="mt-1 text-[13px] font-black text-[#17355f]">{money(x[1])}</div><div className="mt-1 text-[7px] text-[#7e90a9]">{x[3] as string}</div></div>)}</div></section></div>
  <section id="finance-details" className="grid grid-cols-1 gap-2 xl:grid-cols-3"><div className="rounded-[10px] border border-[#d7e4f1] bg-white p-3 xl:col-span-2"><h2 className="text-[12px] font-black text-[#102d5f]">Business Finance — P&L theo đơn vị</h2><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[720px] text-[8px]"><thead className="bg-[#edf3f8]"><tr>{["Đơn vị","Revenue","COGS","Payroll","OTA","Utilities","OPEX","Unverified"].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{pnl.length?pnl.map(x=><tr key={String(x.business_unit)} className="border-t"><td className="p-2 font-bold">{String(x.business_unit)}</td><td>{money(x.revenue)}</td><td>{money(x.cogs)}</td><td>{money(x.payroll)}</td><td>{money(x.ota_commission)}</td><td>{money(x.utilities)}</td><td>{money(x.operating_expense)}</td><td>{String(x.unverified_count??0)}</td></tr>):<tr><td colSpan={8} className="p-6 text-center text-[#8595aa]">01/10 chưa phát sinh canonical Actual.</td></tr>}</tbody></table></div></div><div className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><h2 className="text-[12px] font-black text-[#102d5f]">Weekly Review</h2><div className="mt-3 space-y-2 text-[9px]">{[["Opening Business Cash",summary.openingBusinessCash],["Business Cash (Book)",summary.bookBusinessCash],["Net Opening Liquidity",summary.netOpeningLiquidity],["Salary Advances",summary.employeeAdvancesOutstanding],["Personal Cash",summary.personalCash],["Tax Reserve",summary.taxReserve],["Emergency Fund",summary.emergencyFund],["OTA Receivable",summary.otaReceivable],["Accounts Payable",summary.knownAp],["Debt Outstanding",summary.bankDebtUsed],["Projected Interest",summary.projectedInterest],["Bank vs Book",summary.bankBookVariance]].map(x=><div key={x[0] as string} className="flex justify-between rounded bg-[#f7faff] p-2"><span>{x[0] as string}</span><b>{money(x[1])}</b></div>)}</div></div></section>
  <section className="grid grid-cols-1 gap-2 xl:grid-cols-2"><div className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><h2 className="text-[12px] font-black text-[#102d5f]">OTA Receivables</h2><div className="mt-2 overflow-x-auto"><table className="w-full text-[8px]"><thead className="bg-[#edf3f8]"><tr>{["OTA","Cơ sở","Expected","Received","Outstanding","Status"].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{ar.map(x=><tr key={`${x.ota}-${x.businessUnit}`} className="border-t"><td className="p-2 font-bold">{String(x.ota)}</td><td>{String(x.businessUnit)}</td><td>{money(x.expected)}</td><td>{money(x.received)}</td><td>{money(x.outstanding)}</td><td>{String(x.status)}</td></tr>)}</tbody></table></div></div><div className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><h2 className="text-[12px] font-black text-[#102d5f]">Accounts Payable — Opening 30/09</h2><div className="mt-2 overflow-x-auto"><table className="w-full text-[8px]"><thead className="bg-[#edf3f8]"><tr>{["Đơn vị","Loại","Đối tác","Amount","Due","Status"].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{ap.map((x,i)=><tr key={i} className="border-t"><td className="p-2">{String(x.businessUnit)}</td><td>{String(x.category)}</td><td>{String(x.counterparty)}</td><td>{money(x.amount)}</td><td>{viDate(x.dueDate)}</td><td><span className={`rounded px-2 py-1 ${badge(String(x.verificationStatus))}`}>{statusVi(String(x.verificationStatus))}</span></td></tr>)}</tbody></table></div></div></section>
  <section className="grid grid-cols-1 gap-2 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><h2 className="text-[12px] font-black text-[#102d5f]">Month-End Close — 26 bước</h2><div className="mt-2 max-h-[320px] overflow-y-auto space-y-1">{close.map((x,i)=><div key={i} className="flex items-center justify-between rounded bg-[#f7faff] px-2 py-2 text-[8px]"><span><b>{String(x.step_no??x.step)}.</b> {String(x.description)}</span><span className={`rounded px-2 py-1 font-bold ${badge(String(x.status))}`}>{String(x.status)}</span></div>)}</div></div><div id="transfer-preview" className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><h2 className="text-[12px] font-black text-[#102d5f]">Transfer Preview / L3 Approval</h2><p className="mt-1 text-[8px] text-[#778aa5]">Chỉ chuẩn bị DRAFT + Approval. Không gửi tiền, không thay đổi Actual balance.</p>{proposalApproved?<form action={prepareFinanceTransfer} className="mt-3 grid grid-cols-2 gap-2"><input type="hidden" name="proposal_id" value={proposalId}/><select name="source_account_code" className="rounded border bg-white p-2 text-[9px] text-[#17233d]" required><option value="">Source account</option>{accounts.filter(x=>num(x.bankBalance)!==null).map(a=><option key={String(a.code)} value={String(a.code)}>{String(a.name)} · {money(a.bankBalance)}</option>)}</select><select name="destination_account_code" className="rounded border bg-white p-2 text-[9px] text-[#17233d]"><option value="">External / manual destination</option>{accounts.map(a=><option key={String(a.code)} value={String(a.code)}>{String(a.name)}</option>)}</select><select name="purpose" className="rounded border bg-white p-2 text-[9px] text-[#17233d]" required><option value="OWNER_DISTRIBUTION">Owner Distribution</option><option value="TAX_PAYMENT">Tax Payment</option><option value="TAX_RESERVE_TRANSFER">Tax Reserve Transfer</option><option value="DEBT_REPAYMENT">Debt Repayment</option><option value="BUSINESS_RESERVE">Business Reserve</option><option value="EMERGENCY_USE_APPROVED">Emergency Use Approved</option></select><input name="amount" inputMode="numeric" placeholder="Số tiền" className="rounded border bg-white p-2 text-[9px] text-[#17233d]" required/><button className="col-span-2 rounded bg-[#0874eb] px-3 py-2 text-[9px] font-bold text-white">Chuẩn bị transfer + tạo Approval</button><button type="button" disabled className="col-span-2 rounded bg-slate-200 px-3 py-2 text-[9px] font-bold text-slate-500">GỬI TIỀN — khóa tới khi Approval + Bank execution</button></form>:<div className="mt-4 rounded bg-amber-50 p-3 text-[9px] font-semibold text-amber-800">Chưa có Allocation Proposal APPROVED. Transfer tiếp tục HOLD.</div>}</div></section>
  <details className="rounded-[10px] border border-[#d7e4f1] bg-white p-3"><summary className="cursor-pointer text-[11px] font-black text-[#102d5f]">October Operating Plan · {plan.length} dòng</summary><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[850px] text-[8px]"><thead className="bg-[#edf3f8]"><tr>{["Priority","Domain","BU","Line","Baseline","Target","Gate","Review condition"].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{plan.map((x,i)=><tr key={i} className="border-t"><td className="p-2">{String(x.priority_order??x.priority)}</td><td>{String(x.financial_domain??x.domain)}</td><td>{String(x.business_unit??x.businessUnit)}</td><td>{String(x.line_name??x.name)}</td><td>{money(x.baseline_amount??x.baseline)}</td><td>{money(x.target_amount??x.target)}</td><td>{String(x.gate_status??x.gateStatus)}</td><td>{String(x.review_condition??x.reviewCondition??"—")}</td></tr>)}</tbody></table></div></details>
 </div>
}
